loggers:
  - log
  - slog
  - zap
  - myCustomLogger

sensitive_rules:
  patterns:
    - name: "Any Card"
      regex: '[0-9]{13,16}'
    - name: "GitHub Token"
      regex: 'ghp_[a-zA-Z0-9]{36}'
    - name: "Email Address"
      regex: '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
    - name: "IP Address"
      regex: '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'

  words:
    - password
    - token
    - api_key
    - secret
    - credit_card


output:
  show_in_console: true
  show_suggestions: true
  errors_aggregate: false
  is_test: false