name: Quality Gate

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Tidy dependencies
        run: go mod tidy

      - name: Verify Dependencies
        run: go mod verify

      - name: Run Custom Log Linter
        run: go run ./cmd/linter/main.go ./...
        
