name: Quality Gate

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'
          cache: true

      - name: Prepare Vendor and Testdata
        run: |
          go mod tidy
          go work vendor 
          
          mkdir -p internal/testdata/src/go.uber.org
          cp -aL vendor/go.uber.org/. internal/testdata/src/go.uber.org/
          find internal/testdata/src -name "go.mod" -delete

      - name: Run Tests with Coverage
        run: go test -v -coverprofile=coverage.out ./...

      - name: Build Everything
        run: |
          CGO_ENABLED=1 go build -mod=vendor -buildmode=plugin -o loglint.so ./plugin/main.go
          
          mkdir -p /tmp/lint-build
          cd /tmp/lint-build
          go mod init temp-lint
          
          go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.5
          
          CGO_ENABLED=1 go build -o $GITHUB_WORKSPACE/golangci-lint-bin github.com/golangci/golangci-lint/cmd/golangci-lint
          
          cd $GITHUB_WORKSPACE

      - name: Run golangci-lint
        run: |
          CGO_ENABLED=1 ./golangci-lint-bin run --config=.golangci.yml ./internal/exampleProject/...
        continue-on-error: true

      - name: Check Coverage Threshold
        run: |
          sudo apt-get update && sudo apt-get install -y bc
          total_cov=$(go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+')
          echo "Total coverage: $total_cov%"
          if [ $(echo "$total_cov < 50.0" | bc -l) -eq 1 ]; then
            echo "Error: Coverage is too low ($total_cov%). Expected at least 50%."
            exit 1
          fi